[general]
library_name = "libcimgui"
library_names = {}
output_file_path = "../src/libcimplot.jl"
module_name = ""
jll_pkg_name = ""
jll_pkg_extra = []
export_symbol_prefixes = ["ImPlot", "IMPLOT"]
prologue_file_path = "./prologue.jl"
epilogue_file_path = "./epilogue.jl"
printer_blacklist = ["ImPlotPoint_ImPlotPointNil",
                     "ImPlotPoint_destroy",
                     "ImPlotPoint_ImPlotPointdouble",
                     "ImPlotPoint_ImPlotPointVec2",
                     "ImPlotRange_ImPlotRangeNil",
                     "ImPlotRange_destroy",
                     "ImPlotRange_ImPlotRangedouble"]
use_julia_native_enum_type = false
print_using_CEnum = true
use_deterministic_symbol = true
is_local_header_only = true
smart_de_anonymize = true
auto_mutability = false
auto_mutability_with_new = false
auto_mutability_blacklist = []
auto_mutability_whitelist = []

[codegen]
use_julia_bool = true
always_NUL_terminated_string = true
is_function_strictly_typed = true
opaque_func_arg_as_PtrCvoid = false
opaque_as_mutable_struct = true
use_ccall_macro = false
wrap_variadic_function = false
field_access_method_list = ["ImPlotInputMap", "ImPlotStyle"]
function_argument_conflict_symbols = []

[codegen.macro]
macro_mode = "disable"
functionlike_macro_whitelist = []
add_comment_for_skipped_macro = true
ignore_header_guards = true
ignore_header_guards_with_suffixes = []
ignore_pure_definition = true
